
# Starting robot state.
moveit_msgs/RobotState robot_state

# Starting world state.
WorldState world_state

PrimitivePlan[] plans

BinState[] bin_states

---

bool[] collision

PrimitivePlan[] plans
