# Motion plan request

# Starting robot state.
moveit_msgs/RobotState robot_state

# Starting world state.
WorldState world_state

# The primitive action to create a dense joint trajectory for.
PrimitiveAction action

# Bin states
BinState[] bin_states

# If this flag is true, only check that the input action is collision
# free.
bool only_check_collisions

# Only check end state to see if the grasp is impossible (i.e. in
# collision with the shelf or non-items)
bool check_for_impossible_grasp

---
# Motion plan response

# Is the trajectory valid.
bool valid

# Is the plan collision free.
bool collision_free

# The dense joint trajectory is returned stored in this action.
PrimitiveAction action
