
# Starting robot state.
moveit_msgs/RobotState robot_state

# Starting world state.
WorldState world_state

PrimitivePlan[] grasps

BinState[] bin_states

---

bool[] collision_free

PrimitivePlan[] pregrasps
