
# Starting robot state.
moveit_msgs/RobotState robot_state

# Starting world state.
WorldState world_state

# Pre-bin pose.
PrimitiveAction prebin_pose

PrimitiveAction[] actions

BinState[] bin_states

---

PrimitiveAction[] actions
