# Vision
# Camera Serial examples:
#   Chrichton chest kinect: "503233542542"
#   Primesense: "primesense"

std_msgs/String camera_id
apc_msgs/BinInfo[12] bins # 12 bins, baby
---
apc_msgs/BinState[12] bin_contents