#!/usr/bin/env python
#
# Copyright (c) 2015, Georgia Tech Research Corporation
# All rights reserved.
#
# Author(s): Eric Huang <ehuang@gatech.edu>
# Georgia Tech Socially Intelligent Machines Lab
# Under Direction of Prof. Andrea Thomaz <athomaz@cc.gatech.edu>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above
#       copyright notice, this list of conditions and the following
#       disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials
#       provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# ''AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.

import os
import subprocess
import shutil
from xml.dom import minidom
import rospy
import rospkg

def main():
    # Get path to models.
    rospack = rospkg.RosPack()
    path = rospack.get_path('apc_description')
    # Walk the object model directory.
    for root, subdirs, files in os.walk(path + '/' + 'objects'):
        # Split the path into head and tail.
        object_dir, object_name = os.path.split(root)
        apc_dir, tail = os.path.split(object_dir)
        if tail == "objects":

            kinbody_dir = os.path.join(root, 'kinbody')
            reduced_kinbody_dir = os.path.join(root, 'reduced_kinbody')
            reduced_meshes_dir = os.path.join(root, 'reduced_meshes')

            git_adds = ' ' + os.path.join(kinbody_dir, 'recommended.kinbody.xml')
            git_adds += ' ' + os.path.join(reduced_meshes_dir, object_name + '.stl')
            git_adds += ' ' + os.path.join(reduced_kinbody_dir, 'kinbody.0.xml')
            git_adds += ' ' + os.path.join(reduced_kinbody_dir, 'kinbody.1.xml')
            git_adds += ' ' + os.path.join(reduced_kinbody_dir, 'kinbody.2.xml')
            git_adds += ' ' + os.path.join(reduced_kinbody_dir, 'kinbody.3.xml')
            git_adds += ' ' + os.path.join(reduced_kinbody_dir, 'kinbody.4.xml')
            git_adds += ' ' + os.path.join(reduced_kinbody_dir, 'kinbody.5.xml')
            git_adds += ' ' + os.path.join(reduced_kinbody_dir, 'kinbody.6.xml')
            git_adds += ' ' + os.path.join(reduced_kinbody_dir, 'kinbody.7.xml')
            git_adds += ' ' + os.path.join(reduced_kinbody_dir, 'kinbody.8.xml')
            git_adds += ' ' + os.path.join(reduced_kinbody_dir, 'kinbody.9.xml')

            cmd = 'cd ' + root + ' && git add ' + git_adds
            # print cmd
            print '========================================'
            subprocess.call(cmd, shell=True)


if __name__ == "__main__":
    main()
