#!/bin/sh
#
# Copyright (c) 2015, Georgia Tech Research Corporation
# All rights reserved.
#
# Author(s): Eric Huang <ehuang@gatech.edu>
# Georgia Tech Humanoid Robotics Lab
# Under Direction of Prof. Andrea Thomaz <athomaz@cc.gatech.edu>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above
#       copyright notice, this list of conditions and the following
#       disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials
#       provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# ''AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.

# Find the system path to the urdfs
urdf_path=$(rospack find apc_description)

# List of urdfs
urdfs="lwa4d sdh lwa4d_torso crichton"

# Convert xacro to urdfs to collada
for u in $urdfs; do
    echo "Converting $u.urdf to $u.dae"
    mkdir -p $urdf_path/collada/$u
    # echo "rosrun xacro xacro.py $urdf_path/urdf/$u/$u.xacro -o $urdf_path/collada/$u/$u.urdf"
    rosrun xacro xacro.py $urdf_path/urdf/$u/$u.urdf.xacro -o $urdf_path/collada/$u/$u.urdf
    # echo "rosrun collada_urdf urdf_to_collada $urdf_path/collada/$u/$u.urdf $urdf_path/collada/$u/$u.dae"
    rosrun collada_urdf urdf_to_collada $urdf_path/collada/$u/$u.urdf $urdf_path/collada/$u/$u.dae
    rm $urdf_path/collada/$u/$u.urdf
done
